### ISSUE TITLE
olsr status page not working with latest lede build

### ISSUE THREAD

**Issue by andibraeu** [freifunk-berlin/firmware-wizard-frontend#91]
```
Error: JSON RPC Error: non-zero code 6
    at http://10.36.139.113/index.js:50:119988
    at l (http://10.36.139.113/index.js:44:69738)
    at http://10.36.139.113/index.js:44:70160
    at h.$eval (http://10.36.139.113/index.js:44:77336)
    at h.$digest (http://10.36.139.113/index.js:44:75788)
    at h.$apply (http://10.36.139.113/index.js:44:77619)
    at l (http://10.36.139.113/index.js:44:53134)
    at b (http://10.36.139.113/index.js:44:55535)
    at XMLHttpRequest._.onload (http://10.36.139.113/index.js:44:55933) Possibly unhandled rejection: {}
```

**Comment by andibraeu** [comment]
for now it works...
